### PR TITLE
Add the rule : longURL are generated when shortURL don't existed

### PR DESCRIPTION
**Pull request by duanjunxiao**
Add the rule : longURL are generated when shortURL don't existed

### CODE REVIEW

**Comment by duanjunxiao** [comment]
Add the rule : longURL are generated when shortURL links don't existed

**Comment by andyxning** [comment]
@duanjunxiao Sorry for not understanding your intention. Can you please make an example?

**Comment by duanjunxiao** [comment]
1	https://www.baidu.com/	s1	2017-02-22 16:27:47
2	http://www.google.com	        so	2017-02-22 17:54:48
3	http://www.google.com	        sP	2017-02-22 22:24:04
4	http://www.google.com   	sn	2017-02-22 22:24:07
其实 我就是帮你完善了一下，数据库 不会存多余的信息。你之前一个url可能会对应多个短链接，存之前，判断有直接返回即可，没必要再生成一个新的。

**Comment by andyxning** [comment]
@duanjunxiao 

This is the designed behavior. Please read the first line of [shortme Features](https://github.com/andyxning/shortme#features).

There is a tradeoff.
* same long url to multiple short url(shorme uses)
  *  Pros
    * makes url shortening logic easy, just short every long urls without any further check 
    * be compatible with [goo.gl](https://goo.gl/)
  * Cons
    * this will consume more short urls
    * 
* same long url to single short url(This PR proposed)
  * Pros
    * save sequence space.
  * Cons
    * to quickly query whether there already exists a short url corresponding to the specified long url, we need to create an index for `longurl` whose length is out of control and even we can use partial index for `varchar` type, it's performance may not be acceptable when there are millions of long urls. 

To conclude, the sequence space is large enough for common uses. So, shortme chooses the first  url shortten strategy. This makes shortme easy and more scalable. :)

If you still want to use the second url shortten strategy, i am afraid i will not merge it to shortme. But, you can still apply this PR to you internal version. 

I will close this PR since i do not want to shorme to use the second url shortten stratefy.

**Comment by duanjunxiao** [comment]
OK,I understand.

**Pull request closed without merging**
